version: "3.9"

services:
  sft-service:
    build: .
    container_name: SFT
    restart: always
    ports:
      - 9010:9010
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    command: >
      bash -c "python3 src/manage.py migrate && python3 src/script.py && python3 src/main.py"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 


